name: "nightAngle"
description: "A new Flutter project.̉̉̉̉̉"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  reactive_forms: ^17.0.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  go_router: ^14.2.0
  http: ^1.2.1
  dio: ^5.4.3+1
  awesome_snackbar_content: ^0.1.3
  fpdart: ^2.0.0-dev.3
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  get_storage: ^2.1.1
  dotted_border: ^2.1.0
  reactive_color_picker: ^2.0.1
  flex_color_picker: ^3.5.0
  reactive_image_picker: ^5.0.1
  reactive_file_picker: ^3.0.0
  flutter_iconly: ^1.0.2
  audio_waveforms: ^1.0.5
  flutter_media_metadata: ^1.0.0+1
  flutter_sliding_toast: ^1.1.1
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  neon: ^0.1.0
  animate_do: ^3.3.4
  talker_dio_logger: ^4.3.0
  talker_flutter: ^4.3.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  just_audio_background: ^0.0.1-beta.12
  swipe: ^0.0.1
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  logger: ^2.3.0
  flutter_svg: ^2.0.10+1
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11
  connectivity_plus: ^6.0.3
  just_audio: ^0.9.38
  just_audio_cache: ^0.1.2
  cached_network_image: ^3.3.1
  just_audio_background: ^0.0.1-beta.12

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/animations/
