version: "1"
services:
  postgres:
    container_name: db
    restart: always
    image: postgres:latest

    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nightangle
      POSTGRES_USER: user
      POSTGRES_PASSWORD: bablu007
      POSTGRES_HOST: db
      POSTGRES_HOST_AUTH_METHOD: trust
